package i18n

// Portuguese catalog for internal packages (insights, config errors, settings_meta, gitstatus, scanner, journal, launcher, runner).
func init() {
	register(map[string]string{
		// insights.go — prompt template
		`You are a senior engineer reviewing a developer's daily command log.
Below is the record of terminal commands executed on %s, with their output and exit codes.

Produce an analysis in **markdown** with the following sections:
- ## Day summary — what was done, in 2-4 sentences.
- ## Notable commands — the most relevant ones and why.
- ## Errors and how they were resolved — commands that failed (exit != 0) and the likely cause/solution.
- ## Learnings — practical lessons extracted from the day.
- ## Suggestions — improvements, shortcuts, or next steps.

Be specific and concise. Ignore noise. Do not invent commands that do not appear in the log.`: `Você é um engenheiro sênior revisando o diário de bordo de um desenvolvedor.
Abaixo está o registro dos comandos de terminal executados em %s, com saídas e códigos de saída.

Produza uma análise em **markdown (português do Brasil)** com as seções:
- ## Resumo do dia — o que foi feito, em 2-4 frases.
- ## Comandos notáveis — os mais relevantes e por quê.
- ## Erros e como foram resolvidos — comandos que falharam (exit != 0) e a provável causa/solução.
- ## Aprendizados — lições práticas extraídas do dia.
- ## Sugestões — melhorias, atalhos ou próximos passos.

Seja específico e conciso. Ignore ruído. Não invente comandos que não aparecem no log.`,

		// insights.go — day log separator
		"\n\n--- DAY LOG ---\n\n": "\n\n--- LOG DO DIA ---\n\n",

		// insights.go — Analyze errors
		"no commands recorded on %s": "sem comandos registrados em %s",

		// insights.go — Analyze header
		"# Learnings — %s\n\n_Generated by bvr on %s._\n\n": "# Aprendizados — %s\n\n_Gerado pelo bvr em %s._\n\n",

		// insights.go — callClaude errors
		"failed to call claude: %w (%s)": "falha ao chamar claude: %w (%s)",
		"claude returned empty output":   "claude retornou vazio",

		// insights.go — callAPI errors
		"engine 'api' requires ANTHROPIC_API_KEY (or install the claude CLI and use insightsEngine=auto)": "motor 'api' requer ANTHROPIC_API_KEY (ou instale o claude CLI e use insightsEngine=auto)",
		"invalid API response (%d): %s": "resposta inválida da API (%d): %s",
		"API: %s":                       "API: %s",
		"API returned status %d":        "API retornou status %d",
		"API returned empty content":    "API retornou conteúdo vazio",

		// config.go — Load error
		"invalid config.json: %w": "config.json inválido: %w",

		// config.go — AddProject errors
		"invalid path: %w":            "caminho inválido: %w",
		"path is not a directory: %s": "o caminho não é um diretório: %s",

		// config.go — AddLayout error
		"layout name is required": "nome do layout é obrigatório",

		// config.go — AddPackage error
		"package name is required": "nome do pacote é obrigatório",

		// settings_meta.go — Apply validation error
		"invalid value %q (use: %s)": "valor inválido %q (use: %s)",

		// settings_meta.go — Help strings
		"root directory for project scanning":                    "diretório raiz do scan de projetos",
		"default open mode":                                      "modo padrão de abertura",
		"default launcher shell":                                 "shell padrão do launcher",
		"default run/shell shell":                                "shell padrão do run/shell",
		"engine for learnings analysis":                          "motor da análise de aprendizados",
		"model used on the API path":                             "modelo usado no caminho da API",
		"extra directory to copy analyses to (empty = disabled)": "pasta extra p/ copiar as análises (vazio = desligado)",
		"URL or path to binary for 'bvr upgrade'":                "URL ou caminho do binário p/ 'bvr upgrade'",
		"different color per open tab/window":                    "cor diferente por aba/janela aberta",
		"interface language (en|pt)":                             "idioma da interface (en|pt)",

		// scanner.go — Groups marker
		"group: %d projects": "grupo: %d projetos",

		// journal.go — truncate suffix
		"\n…[truncated]": "\n…[truncado]",
	})
}
